config/routes.rb
Rails.application.routes.draw do
  resources :stories
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/.#application_record.rb
domi91c@mbp.local.34799

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :stories

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/.#stories_controller.rb
domi91c@mbp.local.34799

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # after_action :verify_authorized


  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @author = Story.find(params[:id]).user
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :summary, :genre, :body, :user_id).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Admin', '/admin', class: 'nav-link' %></li>

    <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<style type="text/css">

  .navbar-nav > li > a {
    padding-top: 5px !important;
    padding-bottom: 5px !important;
  }

  .navbar {
    min-height: 50px;
    -webkit-box-shadow: 0px 1px 4px #799db0;
    -moz-box-shadow: 0px 1px 4px #799db0;
    /*box-shadow: 0px 1px 1px #bdbbb6;*/
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.175);
    background-color: rgba(255, 255, 255, 0.98);
  }

  .navbar-toggler-left {
    border: none;
  }

  .nav-user-link {
    color: #7baeca !important;
  }
</style>


<nav class="navbar navbar-toggleable-sm navbar-light bg-faded text-center">
  <%= link_to image_tag('folklit-initial-curved-feather.png', :size => 65, :class => 'navbar-brand mx-auto') %>

  <button class="navbar-toggler navbar-toggler-left" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mx-auto mt-2 mt-md-0 ">
      <%= render 'layouts/navigation_links' %>
    </ul>


    <ul class="navbar-nav pull-right" style="position: relative;">
      <% if user_signed_in? %>
          <li class="nav-item" data-toggle="dropdown"><%= link_to "@#{current_user.username}", '/', class: 'nav-link nav-user-link', style: 'float: right' %></li>
          <ul class="dropdown-menu text-center" role="menu" style="left: -60px">
            <li><a href="#" class="dropdown-item">Profile</a></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
            <li><a href="#" class="dropdown-item">Stories</a></li>
            <li><a href="#" class="dropdown-item">Library</a></li>
          </ul>
      <% else %>
          <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %></li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li class="nav-item"><%= link_to 'Read', stories_path, class: 'nav-link', style: '' %></li>
<li class="nav-item"><%= link_to 'Write', new_story_path, class: 'nav-link', style: '' %></li>
<li class="nav-item"><%= link_to 'People', users_path, class: 'nav-link', style: '' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Folklit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fl" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'medium-editor' %>


    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>

app/views/stories/.#new.html.erb
domi91c@mbp.local.18308

app/views/stories/_form.html.erb
<style>

  .medium-editor-element {
    border: none;
    box-shadow: none;
  }

</style>
<div class="col-md-10 push-1">
  <h2 class=" text-center"><%= @story.title %></h2>
  <h6 class=" text-center">Chapter 2</h6>

  <hr>
  <%= simple_form_for @story, error: false do |f| %>
      <%= f.input :body, class: 'editable', label: false %>
      <br>
      <%= f.submit 'Submit', class: 'btn btn-large btn-primary mt-2' %>
  <% end %>

  <%= link_to 'Show', @story %> |
  <%= link_to 'Back', stories_path %>




</div>
<script>var editor = new MediumEditor('#story_body');</script>

app/views/stories/edit.html.erb
<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tbody>
  <% @stories.each do |s| %>
      <div class="">
        <div class="card-block">
          <h4 class="card-title"><%= link_to s.title, story_path(s), style: 'color: #373a3c' %></h4>
          <h6 class="card-subtitle mb-2 text-muted"><%= s.body.truncate(100) %></h6>
          <div class="story-links">
            <%= link_to 'Edit', edit_story_path(s), data: {turbolinks: false} %>
            |
            <%= link_to 'Preview', edit_story_path(s) %></div>
        </div>
      </div>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path, class: 'btn btn-primary' %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<h2  class=" text-center"><%= @story.title %></h2>
<p class="text-center"><%= link_to "@#{@story.user.username }", user_path(@story.user) %></p>
<hr>



<%= @story.genre %>


<p>
  <%= @story.body.html_safe %>
</p>
<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>